### ISSUE TITLE
collection keyBy / groupBy

### ISSUE THREAD

**Issue by makroxyz** [CalebDW/larastan#19]
- Larastan Version: 2.10.10
- Laravel Version: 11.24.1

### Description
Unable to resolve the template type TNewKey in call to method Illuminate\Support\Collection<int,App\Models\MyModel>::keyBy()  

### Laravel code where the issue was found

```php
$a = MyModel::all()->keyBy('id');
```

Sorry... but I can't understand how to solve this...

**Comment by calebdw** [comment]
Hello!

The framework added better generics in https://github.com/laravel/framework/pull/52787, so now PHPStan can determine what the collection key type should be. However, this only works for closures:

```php
$a = MyModel::all()->keyBy('id');              // Collection<(int|string), MyModel>
$a = MyModel::all()->keyBy(fn ($m) => $m->id); // Collection<int, MyModel>
```

If you want to just use a string, then you can ignore the error locally (or globally):
```php
/** @phpstan-ignore argument.templateType */
$a = MyModel::all()->keyBy('id');
```

This is the best we can do with just PHPDocs, but I'm thinking about writing an extension in Larastan that will be able to determine the type even if an array/string is passed

**Comment by makroxyz** [comment]
Thank you very much!!

Il mer 25 set 2024, 15:50 Caleb White ***@***.***> ha scritto:
